# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-10 01:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('modified', models.DateField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('groupID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('groupPhoto', models.ImageField(null=True, upload_to='group_images')),
                ('modUserID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='modUserID', to=settings.AUTH_USER_MODEL)),
                ('participantUserID', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kyaracter',
            fields=[
                ('modified', models.DateField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('kyaraID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('kyaraname', models.CharField(max_length=50)),
                ('kyarapic', models.ImageField(blank=True, upload_to='kyara_images')),
                ('kyaraowner', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('messageText', models.CharField(default='', max_length=1000)),
                ('messageGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charamain.ChatGroup')),
                ('messageSender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateField(auto_now=True)),
                ('profileDescription', models.CharField(default='', max_length=2000)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('userkyaracount', models.IntegerField(default=0)),
                ('userfriendcount', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
