# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charamain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyaracter',
            name='kyaraID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
