# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charamain', '0003_auto_20170904_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profileDescription',
            field=models.CharField(default='This user has not added a profile description yet', max_length=2000),
        ),
    ]
